server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: 192.168.226.128:9092
    consumer:
      group-id: consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        interceptor:
          classes: com.stc.kafka.MyConsumerInterceptor

    listener:
      ack-mode: manual

# dubbo-provider config
dubbo:
  application:
    name: message-provider
  registry:
    protocol: zookeeper
    address: 192.168.2.96:2181,192.168.2.96:2182,192.168.2.96:2183
  protocol:
    name: dubbo
    port: 10897
  provider:
    version: dev
  scan.base-packages: com.stc.kafka.consumer,com.stc.kafka.aops
  consumer:
    registry: 192.168.2.96:2181,192.168.2.96:2182,192.168.2.96:2183
# dubbo-consumer config
    timeout: 30000
    check: true
    version: dev
# qos config
  application.qos-accept-foreign-ip: false
  application.qos-enable: true
  application.qos-port: 33333